require_relative '04_suggested_track_identifications'

create_users($number_of_users)
create_tracklists_tracks_artists_labels($tracklists, $number_of_users)
create_bookmarked_tracks
create_bookmarked_tracklists
create_suggested_track_identifications